### ISSUE TITLE
Considering creating a ctlptl plugin based on this

### ISSUE THREAD

**Issue by djcp** [virtualstaticvoid/asdf-tilt#2]
Hey! Thanks for this, we're using it internally to get tilt onto dev machines.

 Now that `tilt` wants you to use [`ctlptl`](https://github.com/tilt-dev/ctlptl) as the blessed way to create local k8s backplanes, we need a better way to distribute `ctlptl` to machines. 

Any issues if I essentially copy this plugin to create the `ctlptl` asdf plugin? I know I don't technically have to ask, but thought you might appreciate it.

**Comment by virtualstaticvoid** [comment]
Hi @djcp 

Thanks for the feedback! It's much appreciated.

No issue with you copying this plugin and modifying it as needed for ctlptl.

Cheers
