### ISSUE TITLE
Override arch for M1?

### ISSUE THREAD

**Issue by scalp42** [virtualstaticvoid/asdf-tilt#4]
Hi there,

It'd be great if we would be able to override arch, alike to the [Hashicorp plugin](https://github.com/asdf-community/asdf-hashicorp/blob/aeff16f538295af0a93115fa2ecf62a68ee583e1/bin/install#L120):

```
ASDF_TILT_OVERWRITE_ARCH="arm64" asdf install tilt
```

Let me know your thoughts, cheers.

**Comment by virtualstaticvoid** [comment]
Hi @scalp42 

May I ask why this might be needed?

As an aside, a fix is needed for [bin/install](https://github.com/virtualstaticvoid/asdf-tilt/blob/master/bin/install#L55-L59), since it assumes `arm64` builds are labelled with `_ALPHA`, which is no longer the case for recent releases.

**Comment by scalp42** [comment]
I see, something might be broken then because it installed the x86_64 version for me 🤔

**Comment by virtualstaticvoid** [comment]
If you run [`uname -m`](https://github.com/virtualstaticvoid/asdf-tilt/blob/master/bin/install#L33) from your terminal, what is displayed?

**Comment by scalp42** [comment]
`arm64` indeed 😅

```
$> asdf install tilt
Downloading tilt from https://github.com/tilt-dev/tilt/releases/download/v0.26.1/tilt.0.26.1.mac.x86_64.tar.gz
```

**Comment by virtualstaticvoid** [comment]
Are you sure `uname -m` is returning `arm64`?

The [download filename](https://github.com/virtualstaticvoid/asdf-tilt/blob/master/bin/install#L69) in the message above suggests that [`get_arch()`](https://github.com/virtualstaticvoid/asdf-tilt/blob/master/bin/install#L32-L44) function is returning `x86_64`.

```
Downloading tilt from https://github.com/tilt-dev/tilt/releases/download/v0.26.1/tilt.0.26.1.mac.x86_64.tar.gz
                                                                                                 ^^^^^^
```

In the meantime, I've fixed the `_ALPHA` issue (#5), so please update the plugin using `asdf plugin-update tilt` to get the latest version.

**Comment by scalp42** [comment]
Yes I'm sure, M1 laptop here 😅

**Comment by virtualstaticvoid** [comment]
I can't explain it :confused: 

`uname -m` is used to figure out the architecture to use:

https://github.com/virtualstaticvoid/asdf-tilt/blob/master/bin/install#L32-L44

The returned value is then concatenated into the download filename:

https://github.com/virtualstaticvoid/asdf-tilt/blob/master/bin/install#L46-L71

Which clearly contains `x86_64` in your example.

I think the best way to figure this out is if you edit the `install` script on your local machine (in `~/.asdf/plugins/tilt/bin`) and uncomment `set -x` on [line 5](https://github.com/virtualstaticvoid/asdf-tilt/blob/master/bin/install#L5) to enable logging and then try install another version of tilt, and provide the terminal output.

That should give us a clue as to where it's going wrong.

**Comment by scalp42** [comment]
Sorry for late response been swamped with work @virtualstaticvoid 

I did set it up and it's working fine so I'm a bit confused 😅

```
+ ASDF_INSTALL_TYPE=version
+ TMPDIR=/var/folders/1g/xgptj79j4m719_v5yvp48mwr0000gn/T/
+ '[' -n 0.26.2 ']'
+ '[' -n /Users/scalp/.asdf/installs/tilt/0.26.2 ']'
+ install_tilt version 0.26.2 /Users/scalp/.asdf/installs/tilt/0.26.2
+ local install_type=version
+ local version=0.26.2
+ local install_path=/Users/scalp/.asdf/installs/tilt/0.26.2
+ local bin_install_path=/Users/scalp/.asdf/installs/tilt/0.26.2/bin
++ get_download_url 0.26.2
++ local version=0.26.2
+++ get_platform
++++ uname
++++ tr '[:upper:]' '[:lower:]'
+++ arch=darwin
+++ case ${arch} in
+++ arch=mac
+++ echo mac
++ local platform=mac
+++ get_arch
+++ uname -m
++ local arch=arm64
++ echo https://github.com/tilt-dev/tilt/releases/download/v0.26.2/tilt.0.26.2.mac.arm64.tar.gz
+ local download_url=https://github.com/tilt-dev/tilt/releases/download/v0.26.2/tilt.0.26.2.mac.arm64.tar.gz
+ mkdir -p /Users/scalp/.asdf/installs/tilt/0.26.2/bin
+ local bin_path=/Users/scalp/.asdf/installs/tilt/0.26.2/bin/tilt
+ echo 'Downloading tilt from https://github.com/tilt-dev/tilt/releases/download/v0.26.2/tilt.0.26.2.mac.arm64.tar.gz'
Downloading tilt from https://github.com/tilt-dev/tilt/releases/download/v0.26.2/tilt.0.26.2.mac.arm64.tar.gz
+ curl -sSL https://github.com/tilt-dev/tilt/releases/download/v0.26.2/tilt.0.26.2.mac.arm64.tar.gz -o /Users/scalp/.asdf/installs/tilt/0.26.2/tilt.tar.gz
+ tar xzf /Users/scalp/.asdf/installs/tilt/0.26.2/tilt.tar.gz -C /Users/scalp/.asdf/installs/tilt/0.26.2

+ mv /Users/scalp/.asdf/installs/tilt/0.26.2/tilt /Users/scalp/.asdf/installs/tilt/0.26.2/bin/tilt
+ chmod +x /Users/scalp/.asdf/installs/tilt/0.26.2/bin/tilt
+ rm /Users/scalp/.asdf/installs/tilt/0.26.2/tilt.tar.gz
```

Closing 🤷‍♂️

Thanks again for the help!

**Comment by virtualstaticvoid** [comment]
I figured it out. You are using a different plugin to this one. Probably the one from https://github.com/eaceaser/asdf-tilt which is listed on the plugin index.

**Comment by scalp42** [comment]
Okay, this is a bit funny, mea culpa @virtualstaticvoid 🙈

![](https://media3.giphy.com/media/vX9WcCiWwUF7G/giphy.gif?cid=ecf05e47v5iioe126rcittzhuwznui49yc86k0lpxg23zrsg&rid=giphy.gif&ct=g)
